OUTDIR ?= ../out/

JPP          ?= 
PREPROCESSOR ?=

ARCH_LIST   := amd64
IMPL_LIST   := ref avx2
PARAMS_LIST := 128f 128s 192f 192s 256f 256s
HASH_LIST   := shake
THASH_LIST  := simple robust

JASMIN ?= jasminc
JFLAGS ?= -nowarning ${JADDFLAGS}